---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: react-decorator
  namespace: default
  labels:
    team: personbruker
spec:
  image: navikt/react-decorator:LATEST
  team: personbruker
  port: 80
  ingresses:
    - https://react-decorator.nais.oera-q.local/person/react-decoratoren
    - https://www-q0.nav.no/person/react-dekoratoren
  liveness:
    path: /person/react-decoratoren/isAlive
    initialDelay: 10
  readiness:
    path: /person/react-decoratoren/isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: "3"
      memory: "768Mi"
    requests:
      memory: "512Mi"
